for(i = 0; i <= 10; i++){
    if (i == 0){
        console.log("zero")
    }
    else if (i == 1){
        console.log("um")
    }
    else if (i == 1){
        console.log("um")
    }
    else if (i == 2){
        console.log("dois")
    }
    else if (i == 3){
        console.log("tres")
    }
    else if (i == 4){
        console.log("quatro")
    }
    else if (i == 5){
        console.log("cinco")
    }
    else if (i == 6){
        console.log("seis")
    }
    else if (i == 7){
        console.log("sete")
    }
    else if (i == 8){
        console.log("oito")
    }
    else if (i == 9){
        console.log("nove")
    }
    else if (i == 10){
        console.log("dez")
    }

    
}
